UPDATE groups SET theme = CASE 
WHEN grouptype = 'Access' THEN "Livelihood"
WHEN grouptype = 'Active' THEN "Transportation"
WHEN grouptype = 'Air Quality' THEN "Environmental Concerns"
WHEN grouptype = 'Alternative Energy' THEN "Environmental Concerns"
WHEN grouptype = 'Automobile' THEN "Transportation"
WHEN grouptype = 'Climate Change' THEN "Environmental Concerns"
WHEN grouptype = 'Comfort' THEN "Livelihood"
WHEN grouptype = 'Community' THEN "Livelihood"
WHEN grouptype = 'Conservation' THEN "Environmental Concerns"
WHEN grouptype = 'Design' THEN "Economic Activity"
WHEN grouptype = 'Expenditures' THEN "Economic Activity"
WHEN grouptype = 'Facilities' THEN "Transportation"
WHEN grouptype = 'Health' THEN "Livelihood"
WHEN grouptype = 'Heavy Truck' THEN "Transportation"
WHEN grouptype = 'Mass Transit' THEN "Transportation"
WHEN grouptype = 'Nature' THEN "Environmental Concerns"
WHEN grouptype = 'Pollution' THEN "Environmental Concerns"
WHEN grouptype = 'Product Flow' THEN "Economic Activity"
WHEN grouptype = 'Revenue' THEN "Economic Activity"
WHEN grouptype = 'Safety' THEN "Livelihood"
WHEN grouptype = 'Stresses' THEN "Livelihood"
WHEN grouptype = 'Sustainable' THEN "Environmental Concerns"
WHEN grouptype = 'Technology' THEN "Economic Activity"
WHEN grouptype = 'Visually Pleasing' THEN "Livelihood"
ELSE "9999"
END